a = input('Digite algo: ')
print('O tipo primitivo desse valor é: ', type(a))
print('Só tem espaços? ', a.isspace())
print('É um número? ', a.isnumeric())
print('É alfabético? ', a.isalpha())
print("É alfanumérico? ", a.isalnum())
print('Tem letra maiúscula? ', a.isupper())
print('Tem letras minusculas? ', a.islower())
print('Está capitalisada? ', a.istitle())
